<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\CustomElementsScript.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorCustomElements.ServiceDefaults\BlazorCustomElements.ServiceDefaults.csproj" />
    <ProjectReference Include="..\BlazorCustomElements\BlazorCustomElements.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\CustomElementsScript.js" />
  </ItemGroup>

</Project>
